### PR TITLE
fix-22

### LINKED ISSUE #22: [  FAILED  ] ClientSurfaceEventsTest.buffer_release
```
$ while cmake-build-debug/bin/mir_wlcs_tests --gtest_filter=ClientSurfaceEventsTest.buffer_release; do :; done
```

Expect: continues to pass indefinitely
Actual: After around a minute:

```
Note: Google Test filter = ClientSurfaceEventsTest.buffer_release
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ClientSurfaceEventsTest
[ RUN      ] ClientSurfaceEventsTest.buffer_release
[2018-04-26 11:19:24.699071] mirserver: Selected driver: mir:stub-graphics (version 0.31.2)
[2018-04-26 11:19:24.699280] <DEBUG> mirserver: No session management supported
[2018-04-26 11:19:24.699535] mirserver: Starting
[2018-04-26 11:19:24.706867] mirserver: Using software cursor
[2018-04-26 11:19:24.709797] mirserver: Selected input driver: mir:stub-input (version: 0.31.2)
unable to open lockfile /run/user/1000/snap.clion/wayland-0.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-1.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-2.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-3.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-4.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-5.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-6.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-7.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-8.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-9.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-10.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-11.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-12.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-13.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-14.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-15.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-16.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-17.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-18.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-19.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-20.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-21.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-22.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-23.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-24.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-25.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-26.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-27.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-28.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-29.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-30.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-31.lock check permissions
unable to open lockfile /run/user/1000/snap.clion/wayland-32.lock check permissions
[2018-04-26 11:19:24.711140] mirserver: Mir version 0.31.2
[2018-04-26 11:19:24.711689] mirserver: Initial display configuration:
[2018-04-26 11:19:24.711722] mirserver: * Output 1: VGA connected, used
[2018-04-26 11:19:24.711752] mirserver: . |_ Physical size 0.0" 0x0mm
[2018-04-26 11:19:24.711766] mirserver: . |_ Power is on
[2018-04-26 11:19:24.711780] mirserver: . |_ Current mode 1600x1600 60.00Hz
[2018-04-26 11:19:24.711794] mirserver: . |_ Preferred mode 1600x1600 60.00Hz
[2018-04-26 11:19:24.711806] mirserver: . |_ Orientation normal
[2018-04-26 11:19:24.711820] mirserver: . |_ Logical size 1600x1600
[2018-04-26 11:19:24.711832] mirserver: . |_ Logical position +0+0
[2018-04-26 11:19:24.711844] mirserver: . |_ Scaling factor: 1.00
/home/alan/display_server/mir/tests/acceptance-tests/wayland/wlcs/tests/test_surface_events.cpp:566: Failure
Value of: buffer_released[1]
  Actual: false
Expected: true
[2018-04-26 11:19:24.714914] mirserver: Stopping
[  FAILED  ] ClientSurfaceEventsTest.buffer_release (22 ms)
[----------] 1 test from ClientSurfaceEventsTest (22 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (22 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ClientSurfaceEventsTest.buffer_release
```

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Block in create_visible_surface() until we get a frame callback. (Fixes #22)

Otherwise test logic using frame callbacks becomes racy.

Also disabled CopyCutPaste.given_source_has_offered_data_sink_sees_offer as it isn't obvious why that's broken.

### CODE REVIEW

File: tests/copy_cut_paste.cpp [hunk 1]
```diff
@@ -65,7 +65,7 @@ struct MockDataDeviceListener : DataDeviceListener
 };
 }
 
-TEST_F(CopyCutPaste, given_source_has_offered_data_sink_sees_offer)
```
Comment (wmww) [inline tests/copy_cut_paste.cpp]: Alternatively, we could just move the bad buffer test to be the first one run and not have to disable any.

**Comment by wmww** [comment]
On second thought, we can do that later.
bors r+
