### PR TITLE
[ppa] fix LP credentials and PPAs

### LINKED ISSUE #229: PPA upload not working
https://github.com/MirServer/wlcs/actions/workflows/ppa-upload.yml

### PR DESCRIPTION
**Pull request by Saviq**
Fixes #229 

---

There isn't a `mir-team/wlcs` PPA, but do we even want it?

### CODE REVIEW

File: tools/ppa-upload.sh [hunk 1]
```diff
@@ -97,7 +103,7 @@ series = ubuntu.getSeries(name_or_version=os.environ['RELEASE'])
 
 mir_team = lp.people["mir-team"]
 rc_ppa = mir_team.getPPAByName(name="wlcs-rc")
-release_ppa = mir_team.getPPAByName(name="wlcs")
+release_ppa = mir_team.getPPAByName(name="release")
```
Comment (RAOF) [inline tools/ppa-upload.sh:106]: Hm. This is going to cause WLCS releases to immediately hit the Mir release PPA, which was not our plan. The plan was to manually copy from a WLCS release PPA (which it seems I neglected to actually set up!) into Mir release PPA when we were ready, as new WLCS releases can result in Mir CI failing.

That said, new WLCS releases aren't exactly a daily occurrence *and* we now have very good tools for marking WLCS tests as expected-fail, so maybe direct-to-Mir-release *is* the right choice now.

Comment (Saviq) [reply tools/ppa-upload.sh:106]: Yeah I believe we need to re-think this a bit. Do we need separate `wlcs-` PPAs? Don't we hide things by not running Mir `-dev` with WLCS `dev` until such a time they meet in the Mir release PPA?

Comment (RAOF) [reply tools/ppa-upload.sh:106]: The idea was that if we push WLCS builds straight into Mir CI then WLCS can break Mir CI without any code changes in Mir, which is a bit annoying.

That said, it would be easy to notice breakage and, as I said, we now have good tools for `XFAIL`ing tests, so maybe we *should* be breaking Mir CI early?

Comment (RAOF) [reply tools/ppa-upload.sh:106]: Which is to say: @AlanGriffiths, @wmww, @graysonguarino: opinions?

Comment (Saviq) [reply tools/ppa-upload.sh:106]: I'd 👍 just using `mir-team/dev`, `/rc`, `/release` PPAs for WLCS.

Comment (AlanGriffiths) [reply tools/ppa-upload.sh:106]: I don't think there's an approach without drawbacks. Let's just try it, if it breaks we will fix.

**Review by RAOF — APPROVED** [review]
With that roaring sound of approval,

bors r+
